### ISSUE TITLE
Webpack takes infinite to finish the build

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/katuma-web#35]
I can't manage to boot the frontend with `yarn run dev`. The issue I found is:

```
ubuntu@katuma:~/katuma-web$ NODE_PORT=3002 NODE_HOST='0.0.0.0' yarn run dev
yarn run v0.17.10
$ concurrent --kill-others "yarn run watch-client" "yarn run start-dev"
[0] yarn run v0.17.10
[1] yarn run v0.17.10
[1] $ node ./node_modules/better-npm-run start-dev
[0] $ node ./node_modules/better-npm-run watch-client
[1] running better-npm-run in /home/ubuntu/katuma-web
[0] running better-npm-run in /home/ubuntu/katuma-web
[0] Executing script: watch-client
[0]
[0] to be executed:NODE_PATH=./src UV_THREADPOOL_SIZE=100 node webpack/webpack-dev-server.js
[1] Executing script: start-dev
[1]
[1] to be executed:API_PORT=3000 NODE_PORT=8000 NODE_ENV=development NODE_PATH=./src node --debug ./bin/server.js
[1] Debugger listening on [::]:5858
[0] ==> 🚧  Webpack development server listening on port 3003
[1] Debugger listening on [::]:5859
[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)
...
[0] ./~/redux-actions/~/lodash/_baseKeys.js
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/redux-actions/~/lodash/isEmpty.js 1:15-37
[0] ./~/dom-helpers/activeElement.js
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/react-bootstrap/lib/Dropdown.js 29:21-57
[0] ./~/react-overlays/lib/Modal.js
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/react-bootstrap/lib/Modal.js 53:13-48
[0] ./~/redux-actions/~/lodash/_DataView.js
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/redux-actions/~/lodash/_getTag.js 1:15-37
[0] ./~/redux-form/~/lodash/_ListCache.js
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/redux-form/~/lodash/_Stack.js 1:16-39
[0] ./~/react-bootstrap/~/core-js/library/fn/object/create.js
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/react-bootstrap/~/babel-runtime/core-js/object/create.js 1:30-73
[0] ./~/redux-form/~/lodash/_mapCacheDelete.js
[0] Module build failed: Error: EIO: i/o error, read
...
[0] Module build failed: Error: EIO: i/o error, read
[0]     at Error (native)
[0]  @ ./~/react-redux/~/lodash/isPlainObject.js 1:19-45
[0] chunk global_styles [entry]
[0] [name]-[hash].js
[0] EIO: i/o error, read
[0] Error: EIO: i/o error, read
[0]     at Error (native)
[0]     at Object.fs.readSync (fs.js:603:19)
[0]     at Object.fs.readFileSync (fs.js:433:24)
[0]     at Object.Module._extensions..js (module.js:415:20)
[0]     at Module.load (module.js:343:32)
[0]     at Function.Module._load (module.js:300:12)
[0]     at Module.require (module.js:353:17)
[0]     at require (internal/module.js:12:17)
[0]     at Template.<anonymous> (/home/ubuntu/katuma-web/node_modules/webpack/lib/JsonpMainTemplatePlugin.js:141:87)
[0]     at Template.applyPlugins [as applyPluginsWaterfall] (/home/ubuntu/katuma-web/node_modules/tapable/lib/Tapable.js:37:47)
[0] chunk main [entry]
[0] [name]-[hash].js
```

I recall we had FS issues (the VM setting the FS to read-only due to apparently timeouts on wrtting to disk) when using npm that got solved using yarn. Did anyone experience the same? Sounds related to that old failure?

**Comment by enricostano** [comment]
Yep it seems a similar issue, never seen again after moving to `yarn`. :/

**Comment by enricostano** [comment]
BTW, with @edulan we've been able to install and run both backend and frontend in a vagrantbox VM on a Ubuntu host. Could this be related to some issue between some version of virtualbox and Mac OSX?
